# Site settings
title: SchoolBus 
email: ne@makerstorage.com
description: > # this means to ignore newlines until "baseurl:"
  MakerStorage LLC. is an open source hardware development company.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://makerstorage.com" # the base hostname & protocol for your site
twitter_username: makerstorage
github_username:  makerstorage

# Build settings
markdown: kramdown
